"""Adiciona data de criacao nas doacoes

Revision ID: 6b20d69ad7c3
Revises: edc5ba8906d0
Create Date: 2026-03-19 10:27:52.602726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b20d69ad7c3'
down_revision = 'edc5ba8906d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation', 'created_at')
    # ### end Alembic commands ###
