"""adiciona campo claimed_by a doacao

Revision ID: edc5ba8906d0
Revises: 84e9e1f92736
Create Date: 2025-08-17 18:28:02.400180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc5ba8906d0'
down_revision = '84e9e1f92736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['claimed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('claimed_by_id')

    # ### end Alembic commands ###
